# Generated by Django 4.2.11 on 2024-03-17 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lsmapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "author_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Author Name")),
                (
                    "nationality",
                    models.CharField(max_length=50, verbose_name="Nationality"),
                ),
                ("birth_year", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                max_length=50,
                on_delete=django.db.models.deletion.CASCADE,
                to="lsmapp.author",
            ),
        ),
    ]
