# Generated by Django 4.2.11 on 2024-03-17 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lsmapp", "0002_author_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_img",
            field=models.ImageField(
                blank=True,
                help_text="Provide a book image.",
                null=True,
                upload_to="media/images/",
                verbose_name="Book Image",
            ),
        ),
        migrations.CreateModel(
            name="Load",
            fields=[
                (
                    "load_id",
                    models.URLField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("loan_date", models.DateField()),
                ("return_date", models.DateField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lsmapp.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
